giftCertificate.radio.paper= Paper Gift Certificate
giftCertificate.radio.email=  Email Gift Certificate
giftCertificate.Personalize.button= Personalize Your Gift Certificate
giftCertificate.Amount.button=Amount
giftCertificate.select.button=Select
giftCertificate.type=Gift Certificate Type
giftCertificate.FirstName=First Name:
giftCertificate.LastName=Last Name:
giftCertificate.email=Email:
giftCertificate.modal.firtsname=First Name
giftCertificate.modal.lastname=Last Name
giftCertificate.modal.email=Email Address
giftCertificate.modal.title=Personalize Your Gift Certificate
giftCertificate.modal.close=close
giftCertificate.modal.invalid=Invalid email address.








