saveForLater.button.productCard= Save for Later
saveForLater.item.moved=Item moved to Save for Later!
saveForLater.item.moved.Error=Error While Moving Item!
saveForLater.item.removed.error=Failed to remove item. Please try again.
AddToCart.Error=Failed to add product to cart.
CurrentBasket.Error=No Basket.
Invalid.ProductId=Invalid ProductId.
title.savedforlater=Saved for Later
info.nosaveditems=No Items
label.price=Price
label.quantity=Quantity
button.remove=Remove
button.addtocart=Add To Cart
product.not.found=Product Not Found
saveForLater.list.not.found=Save For Later List Not Found.




