
wishlist.remove.success=Product has been removed from your wishlist.
wishlist.remove.error=Unable to remove the product from your wishlist. Please try again.
wishlist.toggle.success.add=Product Added to Wishlist.
wishlist.toggle.success.remove=Product Removed from Wishlist.
wishlist.toggle.error.noProduct=The product could not be found.
wishlist.toggle.error=An error occurred.
wishlist.toggle.button.add=Add to Wishlist.
wishlist.toggle.button.remove=Remove from Wishlist.
wishlist.productID=productID:
wishlist.masterID=Master product ID.
wishlist.price=Price:
wishlist.remove.button=Remove.
wishlist.empty=Your Wishlist Is Empty.
wishlist.title=Your Wishlist.
wishlist.error=Error.



