## cartridge.properties for cartridge app_storefront_base
#Thu Jun 09 11:30:40 EDT 2016
demandware.cartridges.custom_sanika1.multipleLanguageStorefront=true
demandware.cartridges.custom_sanika1.id=app_storefront_base
demandware.cartridges.custom_sanika1.version=7.0.1
