review.success.message=Review submitted successfully!
review.already.submitted.message=You have already submitted a review for this product.
review.error.message=An error occurred while submitting your review.
review.submit.url=https://zzon-002.dx.commercecloud.salesforce.com/on/demandware.store/Sites-SanikaWadake-Site/default/SubmitReview-start

order.details.url=https://zzon-002.dx.commercecloud.salesforce.com/on/demandware.store/Sites-SanikaWadake-Site/default/Order-Details?orderID={orderID}&orderFilter=
order.details.click.here=Click here to view your order details.

label.order.viewDetails=Click here to view your order details.

modal.rating.select=Select a rating
modal.rating.title=Submit Your Rating and Review
modal.rating.label=Rating
modal.rating.option1=1
modal.rating.option2=2
modal.rating.option3=3
modal.rating.option4=4
modal.rating.option5=5
modal.review.label=Review
modal.button.close=Close
modal.button.submit=Submit
card.modal.rating.title=Ratings and Review


ratings.reviews.title=Customer Reviews for Product ID:
ratings.reviews.heading=Customer Reviews
ratings.reviews.orderId=Order ID:
ratings.reviews.review=Review:
ratings.reviews.rating=Rating:
ratings.reviews.showMore=Show More
ratings.reviews.noReviews=No customer reviews available for this product.
ratings.reviews.noRatings=No ratings and reviews found for this product.

default.ratings=5


